# Generated by Django 5.1.5 on 2025-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_address',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
    ]
