# Generated by Django 5.1.5 on 2025-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_adoptionrequest_adopter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='request_date',
            field=models.DateTimeField(),
        ),
    ]
